environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  - git submodule update --recursive 
  - dir

  # installs meteor using Chocolatey
  - cinst meteor

  # accounts for PATH variable change after meteor installation
  - refreshenv

  # install modules
  - npm install --global yarn

  - python.exe --version
  # node-gyp requirement
  - npm install --global windows-build-tools

  - yarn

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests

  - yarn gulp --mist --win
  - yarn gulp --wallet --win
  - yarn gulp test
  - yarn test:unit:once

build: off
