image: Visual Studio 2017
platform: x64

shallow_clone: true

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  nodejs_version: "8"

init:
  # enabling RDP for debugging purposes
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # needed for meteor-dapp-wallet
  - git submodule update --init --recursive 
  - dir meteor-dapp-wallet

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  # installs meteor using Chocolatey
  - cinst meteor

  # installs makensis using Chocolatey
  - cinst nsis

  # accounts for PATH variable change after meteor installation
  - refreshenv

  # install modules
  - npm install --global yarn

  - yarn

test_script:
  - yarn build:mist --win --skipTasks=bundling-interface
    # - yarn gulp --wallet --win --skipTasks=build-nsis
  - yarn gulp test
  - yarn test:unit:once

build: off
