image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  nodejs_version: "8"

init:
  # enabling RDP for debugging purposes
  - ps: $blockRdp = true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

  # needed for meteor-dapp-wallet
  - git submodule update --init --recursive 

  # installs global dependencies
  - choco install meteor
  - meteor --version
  
    # Upgrades meteor to get rid of winx64 css build error. TODO: update to a stable version once it's released
    # https://forums.meteor.com/t/meteor-1-7-0-3-deploy-failure/44252
  - meteor update --release 1.7.1-beta.22
  - meteor --version

  - choco install nsis
  - choco install yarn

  # accounts for PATH variable change after meteor installation
  - refreshenv

  # installs JS dependencies
  - yarn install

test_script:
  # Building interface outside gulp scope due to path errors
  # this is a tentative workaround for appveyor
  - yarn build:interface

  - yarn build:mist --win --skipTasks=build-interface
  - yarn gulp --wallet --win --skipTasks=build-interface
  - yarn test:unit:once
  - yarn dist:mist
  - yarn dist:wallet

build: off


